package com.mycompany.tienda.zapatillas.view.menus;

import com.mycompany.tienda.zapatillas.controller.ClienteController;
import java.awt.event.ActionListener;
import javax.swing.JTable;

/**
 * Vista Principal del Administrador. Actúa como el contenedor maestro donde se
 * cargan todas las demás pantallas.
 */
public class MenuAdminView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuAdminView.class.getName());

    // =========================================================================
    // 1. CONSTRUCTOR Y CONFIGURACIÓN INICIAL
    // =========================================================================
    public MenuAdminView() {
        initComponents(); // Carga todo el diseño visual que armaste en NetBeans
        this.setResizable(false); // Bloquea el tamaño para que no desarmen el diseño
        this.setLocationRelativeTo(null); // Centra la ventana en la pantalla al abrir

        // Acá registramos cada panel como si fuera una "carta" de un mazo.
        // Le ponemos un apodo (ej: "cardInventario") para después llamarlo fácil.
        panelPrincipal.add(panelDashboard, "cardDashboard");
        panelPrincipal.add(panelInventario, "cardInventario");
        panelPrincipal.add(panelClientes, "cardClientes");
        panelPrincipal.add(panelEmpleados, "cardEmpleados");
        panelPrincipal.add(panelNuevaVenta, "cardNuevaVenta");
        panelPrincipal.add(panelHistorialVentas, "cardHistorial");
    }

    // =========================================================================
    // 2. MOTOR DE NAVEGACIÓN
    // =========================================================================
    /**
     * Este método recibe el "apodo" de una carta y la pone al frente, ocultando
     * las demás. Así logramos el efecto de cambiar de pantalla.
     */
    public void mostrarPanel(String nombreCard) {
        java.awt.CardLayout layout = (java.awt.CardLayout) panelPrincipal.getLayout();
        layout.show(panelPrincipal, nombreCard);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDashboard = new javax.swing.JPanel();
        btnMenuInventario = new javax.swing.JButton();
        btnMenuClientes = new javax.swing.JButton();
        btnMenuEmpleados = new javax.swing.JButton();
        btnVenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnVerHistorial = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        panelPrincipal = new javax.swing.JPanel();
        panelClientes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        btnAgregarCliente = new javax.swing.JButton();
        btnModificarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtBuscarClientes = new javax.swing.JTextField();
        panelEmpleados = new javax.swing.JPanel();
        btnAgregarEmpleado = new javax.swing.JButton();
        btnModificarEmpleado = new javax.swing.JButton();
        btnEliminarEmpleado = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        txtBuscarUsuarios = new javax.swing.JTextField();
        panelInventario = new javax.swing.JPanel();
        btnReportes = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        btnEliminarProd = new javax.swing.JButton();
        btnModificarProd = new javax.swing.JButton();
        btnAgregarProd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        panelNuevaVenta = new javax.swing.JPanel();
        cmbClientes = new javax.swing.JComboBox<>();
        cmbProductos = new javax.swing.JComboBox<>();
        txtCantidad = new javax.swing.JTextField();
        btnAgregarCarrito = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCarrito = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        btnConfirmarVenta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelHistorialVentas = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaHistorial = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        panelDashboard.setPreferredSize(new java.awt.Dimension(583, 355));

        btnMenuInventario.setText("Inventario");
        btnMenuInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuInventario.addActionListener(this::btnMenuInventarioActionPerformed);

        btnMenuClientes.setText("Clientes");
        btnMenuClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuClientes.addActionListener(this::btnMenuClientesActionPerformed);

        btnMenuEmpleados.setText("Empleados");
        btnMenuEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuEmpleados.addActionListener(this::btnMenuEmpleadosActionPerformed);

        btnVenta.setText("Venta");
        btnVenta.addActionListener(this::btnVentaActionPerformed);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu principal Admin");

        btnVerHistorial.setText("Historial de Ventas");
        btnVerHistorial.addActionListener(this::btnVerHistorialActionPerformed);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Bienvenido!!");

        javax.swing.GroupLayout panelDashboardLayout = new javax.swing.GroupLayout(panelDashboard);
        panelDashboard.setLayout(panelDashboardLayout);
        panelDashboardLayout.setHorizontalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDashboardLayout.createSequentialGroup()
                .addGroup(panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDashboardLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDashboardLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDashboardLayout.createSequentialGroup()
                                .addComponent(btnMenuInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnMenuClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btnMenuEmpleados)
                                .addGap(18, 18, 18)
                                .addComponent(btnVenta)))
                        .addGap(18, 18, 18)
                        .addComponent(btnVerHistorial)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelDashboardLayout.setVerticalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDashboardLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenuEmpleados)
                    .addComponent(btnMenuClientes)
                    .addComponent(btnMenuInventario)
                    .addComponent(btnVenta)
                    .addComponent(btnVerHistorial))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(585, 370));

        panelPrincipal.setLayout(new java.awt.CardLayout());

        panelClientes.setMaximumSize(null);

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "Correo Electrónico"
            }
        ));
        jScrollPane2.setViewportView(tablaClientes);

        btnAgregarCliente.setText("Agregar");
        btnAgregarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarCliente.addActionListener(this::btnAgregarClienteActionPerformed);

        btnModificarCliente.setText("Modificar");
        btnModificarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarCliente.addActionListener(this::btnModificarClienteActionPerformed);

        btnEliminarCliente.setText("Eliminar");
        btnEliminarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarCliente.addActionListener(this::btnEliminarClienteActionPerformed);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("LISTADO DE CLIENTES");

        javax.swing.GroupLayout panelClientesLayout = new javax.swing.GroupLayout(panelClientes);
        panelClientes.setLayout(panelClientesLayout);
        panelClientesLayout.setHorizontalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(btnAgregarCliente)
                        .addGap(41, 41, 41)
                        .addComponent(btnModificarCliente)
                        .addGap(47, 47, 47)
                        .addComponent(btnEliminarCliente))
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelClientesLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtBuscarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelClientesLayout.setVerticalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBuscarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarCliente)
                    .addComponent(btnModificarCliente)
                    .addComponent(btnEliminarCliente))
                .addGap(16, 16, 16))
        );

        panelPrincipal.add(panelClientes, "card3");

        panelEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelEmpleados.setPreferredSize(new java.awt.Dimension(491, 355));

        btnAgregarEmpleado.setText("Agregar");
        btnAgregarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarEmpleado.addActionListener(this::btnAgregarEmpleadoActionPerformed);

        btnModificarEmpleado.setText("Modificar");
        btnModificarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarEmpleado.addActionListener(this::btnModificarEmpleadoActionPerformed);

        btnEliminarEmpleado.setText("Eliminar");
        btnEliminarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarEmpleado.addActionListener(this::btnEliminarEmpleadoActionPerformed);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("LISTADO DE EMPLEADOS");

        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "Correo Electrónico"
            }
        ));
        jScrollPane3.setViewportView(tablaEmpleados);

        txtBuscarUsuarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarUsuariosKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelEmpleadosLayout = new javax.swing.GroupLayout(panelEmpleados);
        panelEmpleados.setLayout(panelEmpleadosLayout);
        panelEmpleadosLayout.setHorizontalGroup(
            panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadosLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEmpleadosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregarEmpleado)
                        .addGap(46, 46, 46)
                        .addComponent(btnModificarEmpleado)
                        .addGap(57, 57, 57)
                        .addComponent(btnEliminarEmpleado)
                        .addGap(120, 120, 120))
                    .addGroup(panelEmpleadosLayout.createSequentialGroup()
                        .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelEmpleadosLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtBuscarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(34, Short.MAX_VALUE))))
        );
        panelEmpleadosLayout.setVerticalGroup(
            panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmpleadosLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBuscarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarEmpleado)
                    .addComponent(btnModificarEmpleado)
                    .addComponent(btnEliminarEmpleado))
                .addGap(43, 43, 43))
        );

        panelPrincipal.add(panelEmpleados, "card2");

        btnReportes.setText("Reportes");
        btnReportes.addActionListener(this::btnReportesActionPerformed);

        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Marca", "Modelo", "Precio", "Stock"
            }
        ));
        jScrollPane4.setViewportView(tablaInventario);

        btnEliminarProd.setText("Eliminar");
        btnEliminarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarProd.addActionListener(this::btnEliminarProdActionPerformed);

        btnModificarProd.setText("Modificar");
        btnModificarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarProd.addActionListener(this::btnModificarProdActionPerformed);

        btnAgregarProd.setText("Agregar");
        btnAgregarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarProd.addActionListener(this::btnAgregarProdActionPerformed);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("INVENTARIO");

        txtBuscar.addActionListener(this::txtBuscarActionPerformed);
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelInventarioLayout = new javax.swing.GroupLayout(panelInventario);
        panelInventario.setLayout(panelInventarioLayout);
        panelInventarioLayout.setHorizontalGroup(
            panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInventarioLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btnAgregarProd)
                .addGap(52, 52, 52)
                .addComponent(btnModificarProd)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarProd)
                .addGap(70, 70, 70)
                .addComponent(btnReportes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelInventarioLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelInventarioLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        panelInventarioLayout.setVerticalGroup(
            panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarProd)
                    .addComponent(btnModificarProd)
                    .addComponent(btnEliminarProd)
                    .addComponent(btnReportes))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelInventario, "card4");

        cmbClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbClientes.addActionListener(this::cmbClientesActionPerformed);

        cmbProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbProductos.addActionListener(this::cmbProductosActionPerformed);

        txtCantidad.addActionListener(this::txtCantidadActionPerformed);

        btnAgregarCarrito.setText("Cargar");
        btnAgregarCarrito.addActionListener(this::btnAgregarCarritoActionPerformed);

        tablaCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Prod", "Modelo", "Cantidad", "Precio Unitario", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tablaCarrito);

        lblTotal.setText("Total: $ 0.00");

        btnConfirmarVenta.setText("CONFIRMAR VENTA");
        btnConfirmarVenta.addActionListener(this::btnConfirmarVentaActionPerformed);

        jLabel5.setText("Cantidad");

        jLabel6.setText("Cliente");

        jLabel7.setText("Producto");

        javax.swing.GroupLayout panelNuevaVentaLayout = new javax.swing.GroupLayout(panelNuevaVenta);
        panelNuevaVenta.setLayout(panelNuevaVentaLayout);
        panelNuevaVentaLayout.setHorizontalGroup(
            panelNuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNuevaVentaLayout.createSequentialGroup()
                .addGroup(panelNuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNuevaVentaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelNuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelNuevaVentaLayout.createSequentialGroup()
                                .addGroup(panelNuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbClientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(panelNuevaVentaLayout.createSequentialGroup()
                                        .addComponent(cmbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(panelNuevaVentaLayout.createSequentialGroup()
                                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAgregarCarrito)))
                                .addGap(18, 18, 18))
                            .addGroup(panelNuevaVentaLayout.createSequentialGroup()
                                .addGroup(panelNuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(lblTotal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(panelNuevaVentaLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnConfirmarVenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        panelNuevaVentaLayout.setVerticalGroup(
            panelNuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNuevaVentaLayout.createSequentialGroup()
                .addGroup(panelNuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNuevaVentaLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelNuevaVentaLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(2, 2, 2)
                        .addComponent(cmbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelNuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarCarrito))
                        .addGap(38, 38, 38)
                        .addComponent(lblTotal)
                        .addGap(31, 31, 31)
                        .addComponent(btnConfirmarVenta)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelNuevaVenta, "card5");

        tablaHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ticket ID", "Fecha", "Cliente", "Vendedor", "Total"
            }
        ));
        jScrollPane5.setViewportView(tablaHistorial);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("HISTORIAL DE VENTAS");

        jButton1.setText("Generar Reporte");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout panelHistorialVentasLayout = new javax.swing.GroupLayout(panelHistorialVentas);
        panelHistorialVentas.setLayout(panelHistorialVentasLayout);
        panelHistorialVentasLayout.setHorizontalGroup(
            panelHistorialVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHistorialVentasLayout.createSequentialGroup()
                .addGroup(panelHistorialVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHistorialVentasLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panelHistorialVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelHistorialVentasLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jButton1)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelHistorialVentasLayout.setVerticalGroup(
            panelHistorialVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHistorialVentasLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(32, 32, 32))
        );

        panelPrincipal.add(panelHistorialVentas, "card6");

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Gestión");

        jMenuItem1.setText("Inventario");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Clientes");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Empleados");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Caja");

        jMenuItem4.setText("Nueva Venta");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Historial de Ventas");
        jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 599, 367);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuInventarioActionPerformed
        this.mostrarPanel("cardInventario");

        // 2. Instanciamos tu ProductoController para que traiga la data de MySQL
        com.mycompany.tienda.zapatillas.controller.ProductoController prodControlador = new com.mycompany.tienda.zapatillas.controller.ProductoController();

        // 3. Le pasamos la tabla visual para que él la llene
        prodControlador.llenarTabla(tablaInventario);
    }//GEN-LAST:event_btnMenuInventarioActionPerformed

    private void btnModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarClienteActionPerformed
        com.mycompany.tienda.zapatillas.controller.ClienteController controlador = 
    new com.mycompany.tienda.zapatillas.controller.ClienteController();

    // 1. Abrimos el formulario (el programa se pausa aquí hasta que cierres el diálogo)
    controlador.abrirFormularioModificar(this, this.tablaClientes);
    
    // 2. UNA VEZ CERRADO EL DIÁLOGO, refrescamos la tabla inmediatamente
    controlador.llenarTabla(this.tablaClientes);
    }//GEN-LAST:event_btnModificarClienteActionPerformed

    private void btnModificarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarEmpleadoActionPerformed
        com.mycompany.tienda.zapatillas.controller.UsuarioController controlador = new com.mycompany.tienda.zapatillas.controller.UsuarioController();
        controlador.abrirFormularioModificar(this);
    }//GEN-LAST:event_btnModificarEmpleadoActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEmpleadoActionPerformed
        com.mycompany.tienda.zapatillas.controller.UsuarioController controlador = new com.mycompany.tienda.zapatillas.controller.UsuarioController();
        controlador.abrirFormularioAgregar(this);
    }//GEN-LAST:event_btnAgregarEmpleadoActionPerformed

    private void btnEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEmpleadoActionPerformed
        com.mycompany.tienda.zapatillas.controller.UsuarioController controlador = new com.mycompany.tienda.zapatillas.controller.UsuarioController();
        controlador.eliminarEmpleado(this);
    }//GEN-LAST:event_btnEliminarEmpleadoActionPerformed

    private void btnEliminarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProdActionPerformed
        com.mycompany.tienda.zapatillas.controller.ProductoController controlador = new com.mycompany.tienda.zapatillas.controller.ProductoController();
        controlador.eliminarProducto(this);
    }//GEN-LAST:event_btnEliminarProdActionPerformed

    private void btnModificarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProdActionPerformed
        com.mycompany.tienda.zapatillas.controller.ProductoController controlador = new com.mycompany.tienda.zapatillas.controller.ProductoController();
        controlador.abrirFormularioModificar(this);
    }//GEN-LAST:event_btnModificarProdActionPerformed

    private void btnAgregarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProdActionPerformed
        com.mycompany.tienda.zapatillas.controller.ProductoController controlador = new com.mycompany.tienda.zapatillas.controller.ProductoController();
        controlador.abrirFormularioAgregar(this);
    }//GEN-LAST:event_btnAgregarProdActionPerformed

    private void btnMenuEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuEmpleadosActionPerformed
        this.mostrarPanel("cardEmpleados");
        com.mycompany.tienda.zapatillas.controller.UsuarioController controlador = new com.mycompany.tienda.zapatillas.controller.UsuarioController();
        controlador.llenarTabla(tablaEmpleados);
    }//GEN-LAST:event_btnMenuEmpleadosActionPerformed

    private void btnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaActionPerformed
        this.mostrarPanel("cardNuevaVenta");
        new com.mycompany.tienda.zapatillas.controller.VentaController().inicializarCaja(this.tablaCarrito, this.lblTotal, this.txtCantidad, this.cmbClientes, this.cmbProductos);
    }//GEN-LAST:event_btnVentaActionPerformed

    private void btnMenuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuClientesActionPerformed
        // 1. Cambiamos la vista al panel de Clientes
        this.mostrarPanel("cardClientes");

        // 2. Instanciamos el controlador para traer la data de MySQL
        com.mycompany.tienda.zapatillas.controller.ClienteController clienteControlador = new com.mycompany.tienda.zapatillas.controller.ClienteController();

        // 3. Le pasamos la tabla visual de clientes (asegurate que se llame tablaClientes)
        clienteControlador.llenarTabla(tablaClientes);
    }//GEN-LAST:event_btnMenuClientesActionPerformed

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        new ClienteController().abrirFormularioAgregar(this, tablaClientes);
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
       new com.mycompany.tienda.zapatillas.controller.ClienteController()
        .eliminarCliente(this, this.tablaClientes);
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void cmbProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProductosActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void btnAgregarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCarritoActionPerformed
        new com.mycompany.tienda.zapatillas.controller.VentaController().agregarAlCarrito(this, this.tablaCarrito, this.cmbClientes, this.cmbProductos, this.txtCantidad, this.lblTotal);
    }//GEN-LAST:event_btnAgregarCarritoActionPerformed

    private void cmbClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbClientesActionPerformed

    private void btnConfirmarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarVentaActionPerformed
       new com.mycompany.tienda.zapatillas.controller.VentaController().confirmarVenta(this, this.tablaCarrito, this.cmbClientes, this.lblTotal);
    }//GEN-LAST:event_btnConfirmarVentaActionPerformed

    private void btnVerHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerHistorialActionPerformed
        this.mostrarPanel("cardHistorial");

        // 2. Llamamos al controlador para que llene la tabla con las ventas reales
        new com.mycompany.tienda.zapatillas.controller.VentaController().llenarTablaHistorial(this.tablaHistorial);
    }//GEN-LAST:event_btnVerHistorialActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // Muestra la pantalla
        this.mostrarPanel("cardEmpleados");
        // Trae los datos de MySQL
        com.mycompany.tienda.zapatillas.controller.UsuarioController usuarioControlador = new com.mycompany.tienda.zapatillas.controller.UsuarioController();
        usuarioControlador.llenarTabla(tablaEmpleados);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Muestra la pantalla
        this.mostrarPanel("cardInventario");
        // Trae los datos de MySQL
        com.mycompany.tienda.zapatillas.controller.ProductoController prodControlador = new com.mycompany.tienda.zapatillas.controller.ProductoController();
        prodControlador.llenarTabla(tablaInventario);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // Muestra la pantalla
        this.mostrarPanel("cardClientes");
        // Trae los datos de MySQL
        com.mycompany.tienda.zapatillas.controller.ClienteController clienteControlador = new com.mycompany.tienda.zapatillas.controller.ClienteController();
        clienteControlador.llenarTabla(tablaClientes);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // Muestra la pantalla de la caja
        this.mostrarPanel("cardNuevaVenta");
        // Carga los combos de productos y clientes fresquitos
       new com.mycompany.tienda.zapatillas.controller.VentaController().inicializarCaja(this.tablaCarrito, this.lblTotal, this.txtCantidad, this.cmbClientes, this.cmbProductos);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // Muestra la pantalla del historial
        this.mostrarPanel("cardHistorial");
        // Carga la tabla con todas las ventas que se hicieron
       new com.mycompany.tienda.zapatillas.controller.VentaController().llenarTablaHistorial(this.tablaHistorial);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        if (txtBuscar.getText().isEmpty()) {
            new com.mycompany.tienda.zapatillas.controller.ProductoController().llenarTabla(tablaInventario);
        } else {
            // Si hay texto, filtramos
            new com.mycompany.tienda.zapatillas.controller.ProductoController().filtrarTabla(tablaInventario, txtBuscar.getText());
        }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarUsuariosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarUsuariosKeyReleased
        String filtro = txtBuscarUsuarios.getText();
    // Llamamos al controlador de usuarios específicamente
    new com.mycompany.tienda.zapatillas.controller.UsuarioController().filtrarTabla(tablaEmpleados, filtro);
    }//GEN-LAST:event_txtBuscarUsuariosKeyReleased

    // =========================================================================
    // MÉTODO MAIN (Punto de arranque de la ventana)
    // =========================================================================
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new MenuAdminView().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCarrito;
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnAgregarEmpleado;
    private javax.swing.JButton btnAgregarProd;
    private javax.swing.JButton btnConfirmarVenta;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnEliminarEmpleado;
    private javax.swing.JButton btnEliminarProd;
    private javax.swing.JButton btnMenuClientes;
    private javax.swing.JButton btnMenuEmpleados;
    private javax.swing.JButton btnMenuInventario;
    private javax.swing.JButton btnModificarCliente;
    private javax.swing.JButton btnModificarEmpleado;
    private javax.swing.JButton btnModificarProd;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnVenta;
    private javax.swing.JButton btnVerHistorial;
    private javax.swing.JComboBox<String> cmbClientes;
    private javax.swing.JComboBox<String> cmbProductos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panelClientes;
    private javax.swing.JPanel panelDashboard;
    private javax.swing.JPanel panelEmpleados;
    private javax.swing.JPanel panelHistorialVentas;
    private javax.swing.JPanel panelInventario;
    private javax.swing.JPanel panelNuevaVenta;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTable tablaCarrito;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTable tablaEmpleados;
    private javax.swing.JTable tablaHistorial;
    private javax.swing.JTable tablaInventario;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtBuscarClientes;
    private javax.swing.JTextField txtBuscarUsuarios;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables

    public void addBtnMenuInventarioListener(ActionListener listener) {
        btnMenuInventario.addActionListener(listener);
    }

    public void addBtnMenuClientesListener(ActionListener listener) {
        btnMenuClientes.addActionListener(listener);
    }

    public void addBtnMenuEmpleadosListener(ActionListener listener) {
        btnMenuEmpleados.addActionListener(listener);
    }

    // ==========================================
    // SECCIÓN INVENTARIO / PRODUCTOS
    // ==========================================
    public void addBtnAgregarProdListener(ActionListener listener) {
        btnAgregarProd.addActionListener(listener);
    }

    public void addBtnModificarProdListener(ActionListener listener) {
        btnModificarProd.addActionListener(listener);
    }

    public void addBtnEliminarProdListener(ActionListener listener) {
        btnEliminarProd.addActionListener(listener);
    }

    // Obtener ID seleccionado de la tabla de productos
    public int getIdProductoSeleccionado() {
        int fila = tablaInventario.getSelectedRow(); // ⚠️ Asegúrate que se llame tblProductos en tu design
        if (fila != -1) {
            return (int) tablaInventario.getValueAt(fila, 0);
        }
        return -1;
    }

    // Modelo para llenar la tabla de productos desde MySQL
    public javax.swing.table.DefaultTableModel getProductoTableModel() {
        return (javax.swing.table.DefaultTableModel) tablaInventario.getModel();
    }

    public javax.swing.JTable getTablaInventario() {
        return tablaInventario;
    }

    public javax.swing.JTable getTablaEmpleados() {
        return tablaEmpleados;
    }

    public javax.swing.JTable getTablaHistorial() {
        return tablaHistorial;
    }

    // ==========================================
    // SECCIÓN CLIENTES
    // ==========================================
    public void addBtnAgregarClienteListener(ActionListener listener) {
        btnAgregarCliente.addActionListener(listener);
    }

    public void addBtnModificarClienteListener(ActionListener listener) {
        btnModificarCliente.addActionListener(listener);
    }

    public void addBtnEliminarClienteListener(ActionListener listener) {
        btnEliminarCliente.addActionListener(listener);
    }

    // Modelo para llenar la tabla de clientes desde MySQL
    public javax.swing.table.DefaultTableModel getClienteTableModel() {
        return (javax.swing.table.DefaultTableModel) tablaClientes.getModel(); // ⚠️ Asegúrate que se llame tblClientes
    }

    public void addBtnMenuVentasListener(ActionListener listener) {
        btnVenta.addActionListener(listener);
    }

    public void addbtnMenuInventarioListener(ActionListener listener) {
        btnMenuInventario.addActionListener(listener);
    }

    public void addbtnMenuClientesListener(ActionListener listener) {
        btnMenuClientes.addActionListener(listener);
    }

    public void addbtnMenuEmpleadosListener(ActionListener listener) {
        btnMenuEmpleados.addActionListener(listener);
    }

    public void addBtnVentaListener(ActionListener listener) {
        btnVenta.addActionListener(listener);
    }

    public javax.swing.JTable getTablaClientes() {
        return tablaClientes;
    }

    // ==========================================
    // GETTERS PARA EL PANEL DE NUEVA VENTA 
    // ==========================================
    public javax.swing.JComboBox<String> getCmbClientes() {
        return cmbClientes;
    }

    public javax.swing.JComboBox<String> getCmbProductos() {
        return cmbProductos;
    }

    public javax.swing.JTextField getTxtCantidad() {
        return txtCantidad;
    }

    public javax.swing.JTable getTablaCarrito() {
        return tablaCarrito;
    }

    public javax.swing.JLabel getLblTotal() {
        return lblTotal;
    }

}
