/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tienda.zapatillas.view.menus;
import java.awt.event.ActionListener;

/**
 *
 * @author Usuario
 */
public class MenuAdminView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuAdminView.class.getName());

    /**
     * Creates new form MenuAdminView
     */
    public MenuAdminView() {
    initComponents();
    this.setSize(1024, 720);
    this.setResizable(false);
    
    // ASIGNACIÓN DE CARD NAMES POR CÓDIGO
    panelPrincipal.add(panelDashboard, "cardDashboard");
    panelPrincipal.add(panelClientes, "cardClientes");
    panelPrincipal.add(panelEmpleados, "cardEmpleados");
}
public void mostrarPanel(String nombreCard) {
        java.awt.CardLayout layout = (java.awt.CardLayout) panelPrincipal.getLayout();
        layout.show(panelPrincipal, nombreCard);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelDashboard = new javax.swing.JPanel();
        btnMenuInventario = new javax.swing.JButton();
        btnMenuClientes = new javax.swing.JButton();
        btnMenuEmpleados = new javax.swing.JButton();
        btnVenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelInventario = new javax.swing.JPanel();
        btnReportes = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        btnEliminarProd = new javax.swing.JButton();
        btnModificarProd = new javax.swing.JButton();
        btnAgregarProd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        panelEmpleados = new javax.swing.JPanel();
        btnAgregarEmpleado = new javax.swing.JButton();
        btnModificarEmpleado = new javax.swing.JButton();
        btnEliminarEmpleado = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        panelClientes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        btnAgregarCliente = new javax.swing.JButton();
        btnModificarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 720));
        getContentPane().setLayout(new java.awt.CardLayout());

        panelPrincipal.setLayout(new java.awt.CardLayout());

        panelDashboard.setPreferredSize(new java.awt.Dimension(111, 177));

        btnMenuInventario.setText("Inventario");
        btnMenuInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuInventario.addActionListener(this::btnMenuInventarioActionPerformed);

        btnMenuClientes.setText("Clientes");
        btnMenuClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnMenuEmpleados.setText("Empleados");
        btnMenuEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuEmpleados.addActionListener(this::btnMenuEmpleadosActionPerformed);

        btnVenta.setText("Venta");

        jLabel1.setText("Menu principal Admin");

        javax.swing.GroupLayout panelDashboardLayout = new javax.swing.GroupLayout(panelDashboard);
        panelDashboard.setLayout(panelDashboardLayout);
        panelDashboardLayout.setHorizontalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDashboardLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(btnMenuInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDashboardLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1))
                    .addGroup(panelDashboardLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnMenuClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMenuEmpleados)
                        .addGap(18, 18, 18)
                        .addComponent(btnVenta)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDashboardLayout.setVerticalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDashboardLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(98, 98, 98)
                .addGroup(panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenuClientes)
                    .addComponent(btnMenuInventario)
                    .addComponent(btnMenuEmpleados)
                    .addComponent(btnVenta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelDashboard, "card3");

        btnReportes.setText("Reportes");
        btnReportes.addActionListener(this::btnReportesActionPerformed);

        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Precio", "Stock"
            }
        ));
        jScrollPane4.setViewportView(tablaInventario);

        btnEliminarProd.setText("Eliminar");
        btnEliminarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarProd.addActionListener(this::btnEliminarProdActionPerformed);

        btnModificarProd.setText("Modificar");
        btnModificarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarProd.addActionListener(this::btnModificarProdActionPerformed);

        btnAgregarProd.setText("Agregar");
        btnAgregarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarProd.addActionListener(this::btnAgregarProdActionPerformed);

        jLabel4.setText("INVENTARIO");

        javax.swing.GroupLayout panelInventarioLayout = new javax.swing.GroupLayout(panelInventario);
        panelInventario.setLayout(panelInventarioLayout);
        panelInventarioLayout.setHorizontalGroup(
            panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInventarioLayout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInventarioLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelInventarioLayout.createSequentialGroup()
                        .addComponent(btnAgregarProd)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarProd)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarProd)
                        .addGap(41, 41, 41)
                        .addComponent(btnReportes)))
                .addGap(83, 83, 83))
        );
        panelInventarioLayout.setVerticalGroup(
            panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInventarioLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReportes)
                    .addComponent(btnEliminarProd)
                    .addComponent(btnModificarProd)
                    .addComponent(btnAgregarProd))
                .addGap(19, 19, 19))
        );

        panelPrincipal.add(panelInventario, "card4");

        panelEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnAgregarEmpleado.setText("Agregar");
        btnAgregarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarEmpleado.addActionListener(this::btnAgregarEmpleadoActionPerformed);

        btnModificarEmpleado.setText("Modificar");
        btnModificarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarEmpleado.addActionListener(this::btnModificarEmpleadoActionPerformed);

        btnEliminarEmpleado.setText("Eliminar");
        btnEliminarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarEmpleado.addActionListener(this::btnEliminarEmpleadoActionPerformed);

        jLabel2.setText("LISTADO DE EMPLEADOS");

        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "Correo Electrónico"
            }
        ));
        jScrollPane3.setViewportView(tablaEmpleados);

        javax.swing.GroupLayout panelEmpleadosLayout = new javax.swing.GroupLayout(panelEmpleados);
        panelEmpleados.setLayout(panelEmpleadosLayout);
        panelEmpleadosLayout.setHorizontalGroup(
            panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadosLayout.createSequentialGroup()
                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEmpleadosLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(btnAgregarEmpleado)
                        .addGap(48, 48, 48)
                        .addComponent(btnModificarEmpleado)
                        .addGap(44, 44, 44)
                        .addComponent(btnEliminarEmpleado))
                    .addGroup(panelEmpleadosLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel2))
                    .addGroup(panelEmpleadosLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        panelEmpleadosLayout.setVerticalGroup(
            panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmpleadosLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarEmpleado)
                    .addComponent(btnModificarEmpleado)
                    .addComponent(btnAgregarEmpleado))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelEmpleados, "card2");

        panelClientes.setMaximumSize(null);

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "Correo Electrónico"
            }
        ));
        jScrollPane2.setViewportView(tablaClientes);

        btnAgregarCliente.setText("Agregar");
        btnAgregarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnModificarCliente.setText("Modificar");
        btnModificarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarCliente.addActionListener(this::btnModificarClienteActionPerformed);

        btnEliminarCliente.setText("Eliminar");
        btnEliminarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setText("LISTADO DE CLIENTES");

        javax.swing.GroupLayout panelClientesLayout = new javax.swing.GroupLayout(panelClientes);
        panelClientes.setLayout(panelClientesLayout);
        panelClientesLayout.setHorizontalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnAgregarCliente)
                        .addGap(49, 49, 49)
                        .addComponent(btnModificarCliente)
                        .addGap(40, 40, 40)
                        .addComponent(btnEliminarCliente))
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel3)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        panelClientesLayout.setVerticalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificarCliente)
                    .addComponent(btnEliminarCliente)
                    .addComponent(btnAgregarCliente))
                .addGap(32, 32, 32))
        );

        panelPrincipal.add(panelClientes, "card3");

        getContentPane().add(panelPrincipal, "card2");

        setBounds(0, 0, 599, 363);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuInventarioActionPerformed

    private void btnModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarClienteActionPerformed

    private void btnModificarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarEmpleadoActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarEmpleadoActionPerformed

    private void btnEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarEmpleadoActionPerformed

    private void btnEliminarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarProdActionPerformed

    private void btnModificarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarProdActionPerformed

    private void btnAgregarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarProdActionPerformed

    private void btnMenuEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuEmpleadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuAdminView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnAgregarEmpleado;
    private javax.swing.JButton btnAgregarProd;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnEliminarEmpleado;
    private javax.swing.JButton btnEliminarProd;
    private javax.swing.JButton btnMenuClientes;
    private javax.swing.JButton btnMenuEmpleados;
    private javax.swing.JButton btnMenuInventario;
    private javax.swing.JButton btnModificarCliente;
    private javax.swing.JButton btnModificarEmpleado;
    private javax.swing.JButton btnModificarProd;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel panelClientes;
    private javax.swing.JPanel panelDashboard;
    private javax.swing.JPanel panelEmpleados;
    private javax.swing.JPanel panelInventario;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTable tablaEmpleados;
    private javax.swing.JTable tablaInventario;
    // End of variables declaration//GEN-END:variables

    public void addBtnMenuInventarioListener(ActionListener listener) {
        btnMenuInventario.addActionListener(listener);
    }
    
    public void addBtnMenuClientesListener(ActionListener listener) {
        btnMenuClientes.addActionListener(listener);
    }

    public void addBtnMenuEmpleadosListener(ActionListener listener) {
        btnMenuEmpleados.addActionListener(listener);
    }

    // ==========================================
    // SECCIÓN INVENTARIO / PRODUCTOS
    // ==========================================
    
    public void addBtnAgregarProdListener(ActionListener listener) {
        btnAgregarProd.addActionListener(listener);
    }

    public void addBtnModificarProdListener(ActionListener listener) {
        btnModificarProd.addActionListener(listener);
    }

    public void addBtnEliminarProdListener(ActionListener listener) {
        btnEliminarProd.addActionListener(listener);
    }

    // Obtener ID seleccionado de la tabla de productos
    public int getIdProductoSeleccionado() {
        int fila = tablaInventario.getSelectedRow(); // ⚠️ Asegúrate que se llame tblProductos en tu design
        if (fila != -1) {
            return (int) tablaInventario.getValueAt(fila, 0);
        }
        return -1; 
    }

    // Modelo para llenar la tabla de productos desde MySQL
    public javax.swing.table.DefaultTableModel getProductoTableModel() {
        return (javax.swing.table.DefaultTableModel) tablaInventario.getModel();
    }

    // ==========================================
    // SECCIÓN CLIENTES
    // ==========================================
    
    public void addBtnAgregarClienteListener(ActionListener listener) {
        btnAgregarCliente.addActionListener(listener);
    }

    public void addBtnModificarClienteListener(ActionListener listener) {
        btnModificarCliente.addActionListener(listener);
    }

    public void addBtnEliminarClienteListener(ActionListener listener) {
        btnEliminarCliente.addActionListener(listener);
    }

    // Modelo para llenar la tabla de clientes desde MySQL
    public javax.swing.table.DefaultTableModel getClienteTableModel() {
        return (javax.swing.table.DefaultTableModel) tablaClientes.getModel(); // ⚠️ Asegúrate que se llame tblClientes
    }
public void addBtnMenuVentasListener(ActionListener listener) {
    btnVenta.addActionListener(listener);
}



    public void addbtnMenuInventarioListener(ActionListener listener) {
        btnMenuInventario.addActionListener(listener); 
    }
    
    public void addbtnMenuClientesListener(ActionListener listener) {
        btnMenuClientes.addActionListener(listener); 
    }

    public void addbtnMenuEmpleadosListener(ActionListener listener) {
        btnMenuEmpleados.addActionListener(listener); 
    }

    public void addBtnVentaListener(ActionListener listener) {
        btnVenta.addActionListener(listener); 
    }
}
